In [1]:
import numpy as np

In [2]:
# create a 1D array using a list
a = np.array([1, 2, 3, 4, 5])    # np.array() is a function that creates a numpy array
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
# create a 2D array using a list of lists
b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
# Creating 3 * 3 array:
c = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# Map a lambda function:

list1 = [3,6,7,5]
list2 = [4,5,1,7]

# the list way to do it: map a function to each element of the list
product_list = list(map(lambda x, y : x * y, list1, list2))
print(product_list)

[12, 30, 7, 35]


In [6]:
# the numpy array way to do it : simply multiply the two arrays
array_1 = np.array(list1)
array_2 = np.array(list2)

array_3 = array_1 + array_2
print(array_3)
print(type(array_3))

[ 7 11  8 12]
<class 'numpy.ndarray'>


In [7]:
# element wise multiplication and obtain as the output as a list.
# Hint Convert the list to an array and then convert the result to a list.

list_1 = [2,3,4,5]
list_2 = [7,8,9,6]
array_1 = np.array(list_1)   # np.array() is a function that creates a numpy array
array_2 = np.array(list_2)  # np.array() is a function that creates a numpy array
product = array_1 * array_2 # element wise multiplication
print(product)   # this will print the product as a numpy array
product_list = product.tolist()  # convert the numpy array to a list
print(product_list)  # this will print the product as a list

[14 24 36 30]
[14, 24, 36, 30]


- np.ones(): Creates an array filled with ones.
- np.zeros(): Creates an array filled with zeros.
- np.arange(): Creates an array with incremental of a fixed step size.
- np.random.random(): create a array of random numbers between 0 and 1.
- np.random.randint(): create a array of random integers between a given range.
- np.linspace(): create a array of fixed length

In [8]:
# Tip : use help to see the syntax when required
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C', *, device=None, like=None)
    Return a new array of given shape and type, filled with ones.

    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    device : str, optional
        The device on which to place the created array. Default: None.
        For Array-API interoperability only, so must be ``"cpu"`` if passed.

        .. versionadded:: 2.0.0
    like : array_like, optional
            Reference object to allow the creation of arrays which are not
            NumPy arrays. If an array-like passed in as ``like`` supports
  

In [9]:
# Creating a 5 * 3 array of ones
np.ones((5,3))  # np.ones() is a function that creates a numpy array filled with ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
# Notice that, by default, numpy creates a float array. To create an integer array, we can specify the dtype parameter.
np.ones((5,3), dtype=int)  # np.ones() is a function that creates a numpy array filled with ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [11]:
# creating array of zeros
np.zeros(4, dtype = int) # np.zeros() is a function that creates a numpy array filled with zeros

array([0, 0, 0, 0])

In [12]:
# array of random numbers
np.random.random([3,4]) # np.random.random() is a function that creates a numpy array filled with random numbers between 0 and 1

array([[0.00691795, 0.6862007 , 0.16321939, 0.57703154],
       [0.04350498, 0.13938654, 0.65981416, 0.55717665],
       [0.43092889, 0.91900647, 0.27825653, 0.68812391]])

In [13]:
# np.arange()
# np.arnage() is the numpy equivalent if range()
# Notice that 10 is included, 100 is not, as in standard python lists

# from 10 to 100 with a step of 3
numbers = np.arange(10, 100, 3) # np.arange() is a function that creates a numpy array with incremental of a fixed step size of 3
print(numbers) # this will print the numbers as a numpy array

[10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70 73 76 79
 82 85 88 91 94 97]


In [14]:
# np.linspace()
# sometimes, you know the length of the array, not the step size

# array of length 25 between 15 and 18
np.linspace(15,18,25) # np.linspace() is a function that creates a numpy array of fixed length between 15 and 18

array([15.   , 15.125, 15.25 , 15.375, 15.5  , 15.625, 15.75 , 15.875,
       16.   , 16.125, 16.25 , 16.375, 16.5  , 16.625, 16.75 , 16.875,
       17.   , 17.125, 17.25 , 17.375, 17.5  , 17.625, 17.75 , 17.875,
       18.   ])

# Few to useful functions
- np.full(): Create a constant array of any number 'n'
- np.title(): create a new array -- by repeating an existing array -- for a particular number of times
- np.eye(): create an identity matrix of a given size
- np.random.randint(): create a array of random integers between a given range.

In [15]:
# Given an integer 'x', create an array of size m*n having all integer values equal to 'x'.
# Hint: Use dtype to specify integer.
x = 1
m = 3
n = 3

# create a 3 * 3 array of ones
array = np.full((m, n), x)  # np.full() is a function that creates a numpy array filled with the given number x
print(array)  # this will print the array as a numpy array

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [16]:
# Create an array of first 10 multiples of 5 using 'arange' function
np.arange(5, 55, 5) # np.arange() is a function that creates a numpy array with incremental of a fixed step size of 5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [17]:
def create_checkerboard(n): # create_checkerboard() is a function that creates a checkerboard pattern of size n*n
    if n % 2 != 0:  # Check if n is even
        raise ValueError("n must be an even integer")  # raise an error if n is not even

    # Create the basic 2×2 pattern
    basic_pattern = np.array([[0, 1], [1, 0]])   # np.array() is a function that creates a numpy array

    # Tile the pattern to create an n×n checkerboard
    checkerboard = np.tile(basic_pattern, (n//2, n//2))  # np.tile() is a function that creates a new array by repeating the existing array for a particular number of times

    return checkerboard # return the checkerboard array

# Example usage
n = 2  # Can be any even integer
checkerboard_matrix = create_checkerboard(n) # create_checkerboard() is a function that creates a checkerboard pattern of size n*n
print(checkerboard_matrix)

[[0 1]
 [1 0]]


# Some attributes of NumPy arrays are:
- shape: Shape of array (n x m)
- dtype: data type (int, float etc.)
- ndim: Number of dimensions (or axes)
- itemsize: Memory used by each array element in bytes

In [18]:
# shape
# shape of the array is (3, 3)
print(c.shape) # c is a 3 * 3 array

# dtype
# data type of the array is int
print(c.dtype) # c is a 3 * 3 array

# ndim
# number of dimensions of the array is 2
print(c.ndim) # c is a 3 * 3 array

# itemsize
# memory used by each array element in bytes is 4
print(c.itemsize) # c is a 3 * 3 array

(3, 3)
int64
2
8


In [19]:
# Find shape and dimension of the array
list_1 = [10,11,12,13]
list_2 = [15,12,13,14]

array_1 = np.array(list_1)   # np.array() is a function that creates a numpy array
array_2 = np.array(list_2)  # np.array() is a function that creates a numpy array

# shape of the array is (4,)
print(array_1.shape) # array_1 is a 1 * 4 array
# shape of the array is (4,)
print(array_2.shape) # array_2 is a 1 * 4 array

# dimension of the array is 1
print(array_1.ndim) # array_1 is a 1 * 4 array
# dimension of the array is 1
print(array_2.ndim) # array_2 is a  1 * 4 array

(4,)
(4,)
1
1


# subset, slice and index and iterate through Arrays

In [20]:
# indexing and sclicing one dimensional array
array_1D = np.arange(10) # np.arange() is a function that creates a numpy array with incremental of a fixed step size of 1
print(array_1D) # this will print the first element of the array

[0 1 2 3 4 5 6 7 8 9]


In [21]:
# third element
print(array_1D[2]) # this will print the third element of the array

# specific elements
print(array_1D[[0, 2, 4]]) # this will print the first, third and fifth element of the array

# slice third element onward
print(array_1D[2:]) # this will print the third element onward of the array

# slice first to third element
print(array_1D[:3]) # this will print the first three elements of the array

# slice first to third element with step of 2
print(array_1D[:3:2]) # this will print the first three elements of the array with step of 2

#slice starting 0 at increment of 2
print(array_1D[0::2]) # this will print the first element of the array with step of 4

2
[0 2 4]
[2 3 4 5 6 7 8 9]
[0 1 2]
[0 2]
[0 2 4 6 8]


In [22]:
# iteration are also similar to lists
for i in array_1D:
    print(i) # this will print the elements of the array one by one

0
1
2
3
4
5
6
7
8
9


In [23]:
# ceate a 2D array
array_2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # np.array() is a function that creates a numpy array
print(array_2D) # this will print the 2D array

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
# third row and second column
print(array_2D[2,1]) # this will print the third row and second column of the array

8


In [25]:
# sclice the third row and all columns
print(array_2D[2, :]) # this will print the third row and all columns of the array

[7 8 9]


In [26]:
# sclice all rows and second column
print(array_2D[: , 1]) # this will print all rows and second column of the array

[2 5 8]


In [27]:
# sclicing all rows and first three column
print(array_2D[: , :3]) # this will print all rows and first column of the array

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Border Rows and Columns

Description:
Extract all the border rows and columns from a 2-D array.

Format:
Input: A 2-D Python list
Output: Four NumPy arrays - First column of the input array, first row of the input array, last column of the input array, last row of the input array respectively.

Example:
Input 1:
[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]
Output 1:
[11 21 31]
[11 12 13 14]
[14 24 34]
[31 32 33 34]

In [28]:
def extract_borders(input_array):
    # Convert input to NumPy array if it's not already
    arr = np.array(input_array)

    # Extract borders
    first_column = arr[:, 0]
    first_row = arr[0, :]
    last_column = arr[:, -1]
    last_row = arr[-1, :]

    return first_column, first_row, last_column, last_row

# Example usage
arr = np.array([[11, 12, 13, 14],
                [21, 22, 23, 24],
                [31, 32, 33, 34]])

first_col, first_row, last_col, last_row = extract_borders(arr)

print(first_col)  # [11 21 31]
print(first_row)  # [11 12 13 14]
print(last_col)   # [14 24 34]
print(last_row)   # [31 32 33 34]

[11 21 31]
[11 12 13 14]
[14 24 34]
[31 32 33 34]


### Let me explain why NumPy is fast using a real-world data science example.
### Consider analyzing temperatures from 1 million weather station readings:

In [29]:
import numpy as np
import time

# create sample data: 1 million temperature readings
temperatures_list = [20.5 + i * 0.001 for i in range(1000000)] # 20.5 is the base temperature and i * 0.001 is the increment
temperatures_array = np.array(temperatures_list) # numpy array of temperatures

# Task : Convert all temperatures from celsius to fahrenheit (F = C * 9/5 + 32)

# using python list
start_time = time.time() # start time
fahrenheit_list = [(temp * 9/5 + 32 for temp in temperatures_list)]  # list comprehension to convert celsius to fahrenheit
list_time = time.time() - start_time # end time

# using numpy array
start_time = time.time() # start time
fahrenheit_array = temperatures_array * 9/5 + 32  # Vectorized operation to convert celsius to fahrenheit
numpy_time = time.time() - start_time # end time

print(f"Python list time: { list_time:.4f} seconds")
print(f"NumPy time: {numpy_time:.4f} seconds")
print(f"NumPy is {list_time/numpy_time:.2f} times faster than Python list.")

Python list time: 0.0002 seconds
NumPy time: 0.0120 seconds
NumPy is 0.02 times faster than Python list.


# Numpy is faster than Python lists because:
- **Vectorization**: NumPy uses vectorized operations, allowing it to perform element-wise operations on entire arrays without the need for explicit loops. This is done using highly optimized C and Fortran libraries under the hood.
- **Memory Efficiency**: NumPy arrays are more memory-efficient than Python lists. They store data in contiguous blocks of memory, which allows for better cache performance and reduces overhead.
- **Broadcasting**: NumPy can automatically expand the dimensions of arrays to perform operations on arrays of different shapes, which reduces the need for manual reshaping and looping.
- **Optimized Libraries**: NumPy is built on optimized libraries like BLAS and LAPACK, which are designed for high-performance numerical computations. These libraries take advantage of low-level optimizations and parallel processing capabilities of modern CPUs.
- **Compiled Code**: NumPy operations are often implemented in compiled code (C or Fortran), which is generally faster than interpreted Python code. This allows NumPy to perform complex calculations more efficiently.
- **Less Overhead**: NumPy arrays have less overhead compared to Python lists. Python lists are heterogeneous and can store different data types, which adds overhead. NumPy arrays are homogeneous, meaning all elements are of the same type, leading to better performance.
- **Contiguous Memory Layout**: NumPy arrays are stored in contiguous memory locations, which allows for better cache locality and faster access times compared to Python lists, which can be scattered in memory.
- **Parallelization**: NumPy can take advantage of multi-core processors and SIMD (Single Instruction, Multiple Data) instructions to perform operations in parallel, further speeding up computations.
- **Less Python Overhead**: NumPy operations involve less overhead from Python's dynamic typing and object management, making them faster for numerical computations.
- **Optimized Algorithms**: NumPy implements many algorithms in a highly optimized manner, taking advantage of mathematical properties and optimizations that are not possible with Python lists.
- **Caching**: NumPy can take advantage of CPU caching mechanisms, which can significantly speed up computations by reducing memory access times.
- **Data Locality**: NumPy arrays are designed to be stored in a contiguous block of memory, which improves data locality and reduces cache misses during computations.

### NumPy is Fundamental in Machine learning for several reasons:

In [30]:
# 1. Data Representation and manipulation:
import numpy as np

# Feature matrix (each row is a sample, each column is a feature)
X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Target values
y = np.array([0, 1, 0])

# 2. Mathematical Operations:
# Matrix multiplication for predictions
weights = np.array([0.1, 0.2, 0.3])
predictions = X.dot(weights)  # Fast matrix multiplication
print(predictions)

# Statistical operations
mean = X.mean(axis=0)  # Mean of each feature
std = X.std(axis=0)   # Standard deviation of each feature
print(mean, std)


# 3. Feature Scaling:
# Standardization (z - score normalization)
def standardize(X):
    return (X - X.mean(axis=0)) / X.std(axis=0)
X_standardized = standardize(X)
print(X_standardized)

# Efficient memory usage:
# Create large datasets efficiently
large_matrix = np.zeros((10000, 1000)) # 10 million elements
print(f"memory size: {large_matrix.nbytes / (1024 * 1024)} MB")  # print memory size in MB

[1.4 3.2 5. ]
[4. 5. 6.] [2.44948974 2.44948974 2.44948974]
[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]
memory size: 76.2939453125 MB


### Multidimensional Arrays
    * Reshape arrays
    * Stack arrays

In [31]:
# Reshape  arrays
a = np.arange(12)
print(a)
# Reshape to 3 rows and 4 columns
a_reshaped = a.reshape(3, 4) # np.reshape() is a function that reshapes the array to the given shape
print(a_reshaped) # this will print the reshaped array
# Reshape to 2 rows and 6 columns
a_reshaped = a.reshape(2, 6) # np.reshape() is a function that reshapes the array to the given shape
print(a_reshaped) # this will print the reshaped array
# Reshape to 4 rows and 3 columns
a_reshaped = a.reshape(4, 3) # np.reshape() is a function that reshapes the array to the given shape
print(a_reshaped) # this will print the reshaped array
a = a.reshape(4, -1) # np.reshape() is a function that reshapes the array to the given shape
print(a) # this will print the reshaped array
a.T # np.transpose() is a function that transposes the array

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [32]:
# Stack arrays
a = np.array([[1, 2], [3, 4]]) # np.array() is a function that creates a numpy array
b = np.array([[5, 6], [7, 8]]) # np.array() is a function that creates a numpy array
print(a)
print("\n")
print(b)

[[1 2]
 [3 4]]


[[5 6]
 [7 8]]


In [33]:
# Stack arrays vertically
c = np.vstack((a,b)) # np.vstack() is a function that stacks the arrays vertically
print(c) # this will print the stacked array

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [34]:
# stack three question :
# Description: Horizontally stack two arrays using hstack, and finally, vertically stack the resultant array with the third array.
a_ = np.array([[1,2] , [5,6]]) # np.array() is a function that creates a numpy array
b_ = np.array([[3,4] , [7,8]]) # np.array() is a function that creates a numpy array
c_ = np.array([9,10,11,12]) # np.array() is a function that creates a numpy array
print(a_)
print("\n")
print(b_)

# Stack arrays horizontally
d_ = np.hstack((a_, b_ )) # np.hstack() is a function that stacks the arrays horizontally
print(d_)
print(c_)

[[1 2]
 [5 6]]


[[3 4]
 [7 8]]
[[1 2 3 4]
 [5 6 7 8]]
[ 9 10 11 12]


In [35]:
# Mathematical operations
# Mathematical operations are similar to lists
# element wise multiplication
array_1 = np.array([1,2,3]) # np.array() is a function that creates a numpy array
array_2 = np.array([4,5,6]) # np.array() is a function that creates a numpy array
array_3 = array_1 * array_2 # element wise multiplication
print(array_3) # this will print the product as a numpy array

# element wise addition
array_3 = array_1 + array_2 # element wise addition
print(array_3) # this will print the sum as a numpy array

# element wise subtraction
array_3 = array_1 - array_2 # element wise subtraction
print(array_3) # this will print the difference as a numpy array

# element wise division
array_3 = array_1 / array_2 # element wise division
print(array_3) # this will print the division as a numpy array

# element wise exponentiation
array_3 = array_1 ** 2 # element wise exponentiation
print(array_3) # this will print the exponentiation as a numpy array

# element wise square root
array_3 = np.sqrt(array_1) # element wise square root
print(array_3) # this will print the square root as a numpy array

# element wise logarithm
array_3 = np.log(array_1) # element wise logarithm
print(array_3) # this will print the logarithm as a numpy array
# element wise sine
array_3 = np.sin(array_1) # element wise sine
print(array_3) # this will print the sine as a numpy array
# element wise cosine
array_3 = np.cos(array_1) # element wise cosine
print(array_3) # this will print the cosine as a numpy array
# element wise tangent
array_3 = np.tan(array_1) # element wise tangent
print(array_3) # this will print the tangent as a numpy array
# element wise hyperbolic sine
array_3 = np.sinh(array_1) # element wise hyperbolic sine
print(array_3) # this will print the hyperbolic sine as a numpy array
# element wise hyperbolic cosine
array_3 = np.cosh(array_1) # element wise hyperbolic cosine
print(array_3) # this will print the hyperbolic cosine as a numpy array
# element wise hyperbolic tangent
array_3 = np.tanh(array_1) # element wise hyperbolic tangent
print(array_3) # this will print the hyperbolic tangent as a numpy array
# element wise exponential
array_3 = np.exp(array_1) # element wise exponential
print(array_3) # this will print the exponential as a numpy array
# element wise absolute
array_3 = np.abs(array_1) # element wise absolute
print(array_3) # this will print the absolute as a numpy array
# element wise floor
array_3 = np.floor(array_1) # element wise floor
print(array_3) # this will print the floor as a numpy array

[ 4 10 18]
[5 7 9]
[-3 -3 -3]
[0.25 0.4  0.5 ]
[1 4 9]
[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[ 1.55740772 -2.18503986 -0.14254654]
[ 1.17520119  3.62686041 10.01787493]
[ 1.54308063  3.76219569 10.067662  ]
[0.76159416 0.96402758 0.99505475]
[ 2.71828183  7.3890561  20.08553692]
[1 2 3]
[1 2 3]


In [36]:
a = np.arange(1,5) # np.arange() is a function that creates a numpy array with incremental of a fixed step size of 1 to 40
print(a)
# The Non NumPy way ! Not Recommended
a_list = [x/(x+1) for x in a]
print(a_list)

[1 2 3 4]
[np.float64(0.5), np.float64(0.6666666666666666), np.float64(0.75), np.float64(0.8)]


In [37]:
# The numpy way: vectorize the function, then apply it
f = np.vectorize(lambda x: x/(x +1)) # np.vectorize() is a function that vectorizes the function
f(a) # this will print the vectorized function applied to the array

array([0.5       , 0.66666667, 0.75      , 0.8       ])

Linear Algebra operations are also supported by numpy.
- np.dot(): dot product
- np.linalg.inv(): inverse of a matrix
- np.linalg.det(): determinant of a matrix
- np.linalg.eig(): eigenvalues and eigenvectors of a matrix
- np.linalg.svd(): singular value decomposition of a matrix
- np.linalg.norm(): norm of a matrix
- np.linalg.solve(): solve a system of linear equations

In [38]:
# np.dot(): dot product
a = np.array([[1,2],
              [3,4],
              [5,6]]) # np.array() is a function that creates a numpy array
b = np.array([[7,8,9],
              [10,11,12]]) # np.array() is a function that creates a numpy array

# dot product
dot_product = np.dot(a, b) # np.dot() is a function that calculates the dot product of two arrays
print(dot_product) # this will print the dot product as a numpy array

[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


In [39]:
# np.linalg.inv(): inverse of a matrix
a = np.array([[1,2],
              [3,4]]) # np.array() is a function that creates a numpy array

# inverse of a matrix
inverse = np.linalg.inv(a) # np.linalg.inv() is a function that calculates the inverse of a matrix
print(inverse) # this will print the inverse of the matrix as a numpy array


[[-2.   1. ]
 [ 1.5 -0.5]]


In [40]:
# np.linalg.det(): determinant of a matrix
a = np.array([[1,2],
              [3,4]]) # np.array() is a function that creates a numpy array
# determinant of a matrix
determinant = np.linalg.det(a) # np.linalg.det() is a function that calculates the determinant of a matrix
print(determinant) # this will print the determinant of the matrix as a numpy array

-2.0000000000000004


In [41]:
# np.linalg.eig(): eigenvalues and eigenvectors of a matrix
a = np.array([[1,2],
              [3,4]]) # np.array() is a function that creates a numpy array
# eigenvalues and eigenvectors of a matrix
eigenvalues, eigenvectors = np.linalg.eig(a) # np.linalg.eig() is a function that calculates the eigenvalues and eigenvectors of a matrix
print(eigenvalues) # this will print the eigenvalues of the matrix as a numpy array

[-0.37228132  5.37228132]


In [42]:
# np.linalg.svd(): singular value decomposition of a matrix
a = np.array([[1,2],
              [3,4]]) # np.array() is a function that creates a numpy array
# singular value decomposition of a matrix
U, S, V = np.linalg.svd(a) # np.linalg.svd() is a function that calculates the singular value decomposition of a matrix
print(U) # this will print the U matrix of the singular value decomposition as a numpy array
print("\n")
print(S) # this will print the S matrix of the singular value decomposition as a numpy array
print("\n")
print(V) # this will print the V matrix of the singular value decomposition as a numpy array

[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]


[5.4649857  0.36596619]


[[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


In [43]:
# np.linalg.norm(): norm of a matrix
a = np.array([[1,2],
              [3,4]]) # np.array() is a function that creates a numpy array
# norm of a matrix
norm = np.linalg.norm(a) # np.linalg.norm() is a function that calculates the norm of a matrix
print(norm) # this will print the norm of the matrix as a numpy array

5.477225575051661


In [44]:
# np.linalg.solve(): solve a system of linear equations
a = np.array([[1,2],
              [3,4]]) # np.array() is a function that creates a numpy array
b = np.array([5,6]) # np.array() is a function that creates a numpy array
# solve a system of linear equations
solution = np.linalg.solve(a, b) # np.linalg.solve() is a function that solves a system of linear equations
print(solution) # this will print the solution of the system of linear equations as a numpy array

[-4.   4.5]
